package com.quadcore.chat.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

//Models a User's information
@Entity
@Table(name = "Users")
public class UserInfo {
	
	//An autogenerated id (unique for each user)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long userid;
	
	@NotNull
	private String username;
	
	@NotNull
	private String password;
	
	@NotNull
	private String email;
	
	//Constructors
	public UserInfo(){}
	public UserInfo(long userid)
	{
		this.userid = userid;
	}
	public UserInfo(String email, String username)
	{
		this.email = email;
		this.username = username;
	}
	public UserInfo(String email, String username, String password)
	{
		this.email = email;
		this.username = username;
		this.password = password;
	}
	
	//Getter and Setter methods
	public long getId()
	{
		return userid;
	}
	
	public String getUsername()
	{
		return username;
	}
	public void setUsername(String username)
	{
		this.username = username;
	}
	
	public String getPassword()
	{
		return password;
	}
	public void setPassword(String password)
	{
		this.password = password;
	}
		
	public String getEmail()
	{
		return email;
	}
	public void setEmail(String email)
	{
		this.email = email;
	}
}
